--------------------------------------------------------
--  File created - Tuesday-March-18-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPANY_CLIENTS
--------------------------------------------------------

  CREATE TABLE "FINACORE"."COMPANY_CLIENTS" 
   (	"CLIENT_ID" NUMBER, 
	"CLIENT_NAME" VARCHAR2(255), 
	"CLIENT_CODE" VARCHAR2(9), 
	"CONTACT" VARCHAR2(15), 
	"EMAIL" VARCHAR2(255), 
	"ADDRESS" CLOB, 
	"STATUS" VARCHAR2(10), 
	"CLIENT_DATE" DATE, 
	 PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("ADDRESS") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))
--------------------------------------------------------
--  DDL for Table COMPANY_TRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "FINACORE"."COMPANY_TRANSACTIONS" 
   (	"TRANSACTION_ID" NUMBER, 
	"TRANSACTION_CODE" VARCHAR2(9), 
	"TRANSACTION_TYPE" VARCHAR2(255), 
	"COMPANY_NAME" VARCHAR2(255), 
	"TRANSACTION_AMOUNT" NUMBER(20,2), 
	"TRANSACTION_DATE" DATE, 
	 PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table LOGIN_USER
--------------------------------------------------------

  CREATE TABLE "FINACORE"."LOGIN_USER" 
   (	"USERNAME" VARCHAR2(15), 
	"PASS" VARCHAR2(15), 
	 UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into FINACORE.COMPANY_CLIENTS
SET DEFINE OFF;
REM INSERTING into FINACORE.COMPANY_TRANSACTIONS
SET DEFINE OFF;
Insert into FINACORE.COMPANY_TRANSACTIONS (TRANSACTION_ID,TRANSACTION_CODE,TRANSACTION_TYPE,COMPANY_NAME,TRANSACTION_AMOUNT,TRANSACTION_DATE) values (17005674,'LN098231','Loan repayment','ABC Inc.',10000,to_date('02-APR-23','DD-MON-RR'));
REM INSERTING into FINACORE.LOGIN_USER
SET DEFINE OFF;
Insert into FINACORE.LOGIN_USER (USERNAME,PASS) values ('FinaCore','Database01');
--------------------------------------------------------
--  Constraints for Table LOGIN_USER
--------------------------------------------------------

  ALTER TABLE "FINACORE"."LOGIN_USER" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table COMPANY_TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "FINACORE"."COMPANY_TRANSACTIONS" ADD PRIMARY KEY ("TRANSACTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Constraints for Table COMPANY_CLIENTS
--------------------------------------------------------

  ALTER TABLE "FINACORE"."COMPANY_CLIENTS" ADD PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
